name: test

on:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_REF_NAME: develop
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Logging Test
        run: echo $BRANCH_NAME
